export { default as Home } from './home/Home'
export { default as Movie } from './home/Movie'
export { default as MovieDetail } from './home/MovieDetail'
export { default as VnPayReturn } from './home/VnPayReturn'
export { default as Cinema } from './home/Cinema'

export { default as Register } from './Register'
export { default as Login } from './Login'

export { default as Profile } from './profile/Profile'
export { default as Ticket } from './profile/Ticket'
export { default as ChangePass } from './profile/ChangePass'
export { default as PrintTicket } from './PrintTicket'

export { default as Dashboard } from './admin/Dashboard'
export { default as UserManage } from './admin/User'
export { default as MovieManage } from './admin/Movie'
export { default as FoodManage } from './admin/Food'
export { default as CinemaManage } from './admin/Cinema'
export { default as RoomManage } from './admin/Room'
export { default as SeatManage } from './admin/Seat'
export { default as ShowtimeManage } from './admin/Showtime'
export { default as TicketManage } from './admin/Ticket'
export { default as ReportManage } from './admin/Report'
export { default as BannerManage } from './admin/Banner'
